Repository microsoft/LLMLingua, pull requests merged in 2023-12, with the labels that each got.

#26 Update README.md
  README.md
Labels: documentation

#27 Fix (LLMLingua): support mps, fix keep_flag out of dimension.
  DOCUMENT.md
  llmlingua/prompt_compressor.py
Labels: bug, feature

#30 Fix(LLMLingua): fix typo in DOCUMENT.md
  DOCUMENT.md
Labels: documentation

#32 Prerelease(LLMLingua): fix the license
  llmlingua/__init__.py
  llmlingua/prompt_compressor.py
  llmlingua/version.py
  setup.py
Labels: documentation

#38 Remove Duplicate Declaration of Loss Function
  llmlingua/prompt_compressor.py
Labels: style
