Repository microsoft/LLMLingua, pull requests merged in 2024-01, with the labels that each got.

#42 Feature(LLMLingua): add slide of AI Time.
  README.md
Labels: documentation

#56 Feature(LLMLingua): add alt-gpt reference
  README.md
Labels: documentation

#54 Fix (LLMLingua): Resolved a potential ZeroDivisionError caused by the actual compression ratio.
  llmlingua/prompt_compressor.py
Labels: bug

#67 Feature(LLMLingua): support phi-2
  DOCUMENT.md
  README.md
Labels: documentation

#69 Feature (LLMLingua): Add Docstring for PromptCompressor Class
  llmlingua/prompt_compressor.py
Labels: documentation, style
