Repository microsoft/LLMLingua, pull requests merged in 2024-02, with the labels that each got.

#81 add structured prompt compress
  llmlingua/prompt_compressor.py
Labels: feature

#87 Hotfix (LLMLingua): fix the out of range
  llmlingua/prompt_compressor.py
Labels: bug

#88 Feature(LLMLingua): update the FAQ
  Transparency_FAQ.md
Labels: documentation

#95 Added unittest for structured_compress_prompt and fixed bugs
  llmlingua/prompt_compressor.py
  tests/test_llmlingua.py
  tests/test_longllmlingua.py
Labels: bug, feature, style

#96 Feature (LLMLingua): support customized compression spec
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/general_issue.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release.yml
  .github/workflows/unittest.yml
  .gitignore
  .pre-commit-config.yaml
  DOCUMENT.md
  Makefile
  README.md
  SECURITY.md
  SUPPORT.md
  Transparency_FAQ.md
  examples/CoT.ipynb
  examples/Code.ipynb
  examples/OnlineMeeting.ipynb
  examples/RAG.ipynb
  examples/RAGLlamaIndex.ipynb
  examples/Retrieval.ipynb
  llmlingua/prompt_compressor.py
  llmlingua/version.py
  setup.cfg
  setup.py
  tests/test_llmlingua.py
  tests/test_longllmlingua.py
Labels: bug, documentation, feature, style

#97 Feature(LLMLingua): add LangChain example
  DOCUMENT.md
  README.md
  Transparency_FAQ.md
  examples/RAGLlamaIndex.ipynb
  tests/test_llmlingua.py
  tests/test_longllmlingua.py
Labels: documentation, feature
