Repository microsoft/LLMLingua, pull requests merged in 2024-03, with the labels that each got.

#99 Feature(LongLLMLingua): update conference
  README.md
Labels: documentation

#102 fix sentence-filter adding separator bug and add document
  README.md
  llmlingua/prompt_compressor.py
  tests/test_llmlingua.py
  tests/test_longllmlingua.py
Labels: documentation, feature

#107 Fix(LLMLingua): fix the release workflows
  .github/workflows/release.yml
Labels: bug

#108 Fix(LLMLingua): fix the release workflow
  .github/workflows/release.yml
Labels: bug

#109 Release(LLMLingua): release v0.2.0
  llmlingua/prompt_compressor.py
  llmlingua/version.py
Labels: documentation, style

#111 Feature(LLMLingua-2): add LLMLingua-2
  .pre-commit-config.yaml
  DOCUMENT.md
  README.md
  Transparency_FAQ.md
  examples/LLMLingua2.ipynb
  examples/OnlineMeeting.ipynb
  experiments/llmlingua2/README.md
  experiments/llmlingua2/data_collection/GPT4_compressor.py
  experiments/llmlingua2/data_collection/README.md
  experiments/llmlingua2/data_collection/collect_data.sh
  experiments/llmlingua2/data_collection/compress.py
  experiments/llmlingua2/data_collection/compression_instructions.json
  experiments/llmlingua2/data_collection/filter.py
  experiments/llmlingua2/data_collection/format_data.py
  experiments/llmlingua2/data_collection/label_word.py
  experiments/llmlingua2/data_collection/utils.py
  experiments/llmlingua2/evaluation/compress.py
  experiments/llmlingua2/evaluation/eval_bbh.py
  experiments/llmlingua2/evaluation/eval_gsm8k.py
  experiments/llmlingua2/evaluation/eval_longbench.py
  experiments/llmlingua2/evaluation/eval_meetingbank_qa.py
  experiments/llmlingua2/evaluation/eval_meetingbank_summary.py
  experiments/llmlingua2/evaluation/eval_zero_scrolls.py
  experiments/llmlingua2/evaluation/metrics.py
  experiments/llmlingua2/evaluation/scripts/compress.sh
  experiments/llmlingua2/evaluation/scripts/evaluate.sh
  experiments/llmlingua2/evaluation/utils.py
  experiments/llmlingua2/model_training/train.sh
  experiments/llmlingua2/model_training/train_roberta.py
  experiments/llmlingua2/model_training/utils.py
  images/LLMLingua-2.png
  images/motivation.png
  llmlingua/__init__.py
  llmlingua/prompt_compressor.py
  llmlingua/utils.py
  llmlingua/version.py
  pyproject.toml
  tests/test_llmlingua.py
  tests/test_llmlingua2.py
  tests/test_longllmlingua.py
Labels: documentation, feature

#112 Feature(LLMLingua-2): update paper link
  README.md
  examples/LLMLingua2.ipynb
Labels: documentation

#115 Prevent duplicate `torch_dtype` kwargs
  llmlingua/prompt_compressor.py
Labels: bug

#117 Feature(LLMLingua-2): fix the title
  README.md
  llmlingua/prompt_compressor.py
Labels: documentation
